global:
  environment: prod
  domain: api.minishop.com
  imageRegistry: your-registry.com/minishop
  
postgresql:
  enabled: true
  auth:
    postgresPassword: your-secure-password
    database: minishop_prod
  persistence:
    enabled: true
    size: 100Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

redis:
  enabled: true
  auth:
    enabled: true
    password: your-redis-password
  master:
    persistence:
      enabled: true
      size: 50Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

kafka:
  enabled: true
  auth:
    enabled: true
    interBrokerPassword: your-kafka-password
  persistence:
    enabled: true
    size: 100Gi
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 200Gi
  alertmanager:
    persistentVolume:
      enabled: true
      size: 50Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi
  adminPassword: your-secure-admin-password

userService:
  enabled: true
  replicaCount: 3
  image:
    repository: minishop/user-service
    tag: v1.0.0
  service:
    port: 8081
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70

productService:
  enabled: true
  replicaCount: 3
  image:
    repository: minishop/product-service
    tag: v1.0.0
  service:
    port: 8082
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70

orderService:
  enabled: true
  replicaCount: 3
  image:
    repository: minishop/order-service
    tag: v1.0.0
  service:
    port: 8083
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70

paymentService:
  enabled: true
  replicaCount: 3
  image:
    repository: minishop/payment-service
    tag: v1.0.0
  service:
    port: 8084
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70

notificationService:
  enabled: true
  replicaCount: 3
  image:
    repository: minishop/notification-service
    tag: v1.0.0
  service:
    port: 8085
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.minishop.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: minishop-tls-prod
      hosts:
        - api.minishop.com