{{- range $serviceName, $service := .Values -}}
{{- if and (kindIs "map" $service) $service.enabled -}}
{{- if has $serviceName (list "userService" "productService" "orderService" "paymentService" "notificationService") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minishop.serviceName" (dict "serviceName" $serviceName "context" $) }}
  labels:
    {{- include "minishop.serviceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "minishop.serviceSelector" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}